DEFAULT_THUMBNAIL_SIZE = 100  # 100 pixels wide
DEFAULT_PAGE_SIZE = 900  # 900 pixels wide
JPG = 'jpg'
PAGES = 'pages'
THUMBNAILS = 'thumbnails'
DOCVERS = 'docvers'
OCR = 'ocr'
S3_WORKER_ADD_DOC_VER = 's3_worker_add_doc_vers'
S3_WORKER_REMOVE_DOC_VER = 's3_worker_remove_doc_vers'
S3_WORKER_REMOVE_DOC_THUMBNAIL = 's3_worker_remove_doc_thumbnail'
S3_WORKER_REMOVE_DOCS_THUMBNAIL = 's3_worker_remove_docs_thumbnail'
S3_WORKER_REMOVE_PAGE_THUMBNAIL = 's3_worker_remove_page_thumbnail'
S3_WORKER_GENERATE_PREVIEW = 's3_worker_generate_preview'
